### ISSUE TITLE
docs build failing

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_DisplayIO_Layout#71]
log from RTD:
```
Running Sphinx v4.5.0
loading translations [en]... done
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.circuitpython.org/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
reading sources... [ 33%] api
WARNING: autodoc: failed to import module 'icon_widget' from module 'adafruit_displayio_layout.widgets'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/icon_widget.py", line 26, in <module>
    import terminalio
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/terminalio.py", line 26, in <module>
    FONT = fontio.BuiltinFont()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/fontio.py", line 31, in __init__
    self._font = ImageFont.load_default()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 361, in load_default
    f._load_pilfont_data(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 107, in _load_pilfont_data
    image.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

WARNING: autodoc: failed to import module 'icon_animated' from module 'adafruit_displayio_layout.widgets'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/icon_animated.py", line 30, in <module>
    from adafruit_displayio_layout.widgets.icon_widget import IconWidget
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/icon_widget.py", line 26, in <module>
    import terminalio
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/terminalio.py", line 26, in <module>
    FONT = fontio.BuiltinFont()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/fontio.py", line 31, in __init__
    self._font = ImageFont.load_default()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 361, in load_default
    f._load_pilfont_data(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 107, in _load_pilfont_data
    image.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

WARNING: autodoc: failed to import module 'flip_input' from module 'adafruit_displayio_layout.widgets'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/flip_input.py", line 27, in <module>
    from terminalio import FONT
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/terminalio.py", line 26, in <module>
    FONT = fontio.BuiltinFont()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/fontio.py", line 31, in __init__
    self._font = ImageFont.load_default()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 361, in load_default
    f._load_pilfont_data(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 107, in _load_pilfont_data
    image.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

WARNING: autodoc: failed to import module 'cartesian' from module 'adafruit_displayio_layout.widgets'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/autodoc/importer.py", line 62, in import_module
    return importlib.import_module(modname)
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/cartesian.py", line 28, in <module>
    import terminalio
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/terminalio.py", line 26, in <module>
    FONT = fontio.BuiltinFont()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/fontio.py", line 31, in __init__
    self._font = ImageFont.load_default()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 361, in load_default
    f._load_pilfont_data(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 107, in _load_pilfont_data
    image.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats


Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 286, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 351, in run
    graph = InheritanceGraph(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 142, in __init__
    classes = self._import_classes(class_names, currmodule)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 153, in _import_classes
    classes.extend(import_classes(name, currmodule))
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 102, in import_classes
    target = try_import(name)
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/sphinx/ext/inheritance_diagram.py", line 71, in try_import
    return import_module(objname)
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/checkouts/latest/adafruit_displayio_layout/widgets/cartesian.py", line 28, in <module>
    import terminalio
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/terminalio.py", line 26, in <module>
    FONT = fontio.BuiltinFont()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/fontio.py", line 31, in __init__
    self._font = ImageFont.load_default()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 361, in load_default
    f._load_pilfont_data(
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFont.py", line 107, in _load_pilfont_data
    image.load()
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/adafruit-circuitpython-displayio-layout/envs/latest/lib/python3.10/site-packages/PIL/ImageFile.py", line 241, in load
    n, err_code = decoder.decode(b)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
The full traceback has been saved in /tmp/sphinx-err-rmrc8_xt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
WARNING: GENERIC_X86 is not fully supported. Some features may not work.
```

**Comment by tekktrik** [comment]
I think this has been resolved since ReadTheDocs is now building correctly!
